"""
Notes Service
-------------
Handles generation and preparation of semester-exam notes.
"""

from ai_service import generate_notes


def create_notes(topic_name, context):
    """
    Generate a 14-mark semester examination answer.
    """

    if not topic_name:
        raise ValueError("Topic name is required.")

    if not context or not context.strip():
        raise ValueError(
            "No study material was found for this topic."
        )

    answer = generate_notes(
        topic_name,
        context
    )

    return {
        "success": True,
        "topic": topic_name,
        "content": answer
    }


def prepare_notes_for_pdf(
    subject,
    unit,
    topic,
    answer
):
    """
    Prepare metadata for PDF generation.

    The actual PDF can be generated later by the Flask
    download endpoint or browser print-to-PDF.
    """

    return {
        "subject": subject,
        "unit": unit,
        "topic": topic,
        "title": f"{topic} - 14 Mark Notes",
        "content": answer
    }


def create_share_text(
    subject,
    unit,
    topic,
    answer
):
    """
    Create clean text for sharing through
    WhatsApp, email, or clipboard.
    """

    return f"""
ACADEMIC AI BOT
==============================

Subject : {subject}
Unit    : {unit}
Topic   : {topic}

14-MARK EXAM NOTES
==============================

{answer}

------------------------------
Generated by Academic AI Bot
""".strip()